-- ====================================================================
-- SKRIP UTAMA SUPABASE: WEBSITE KKN KELOMPOK 3 DESA KARANGREJO
-- Eksekusi skrip ini di Supabase SQL Editor (https://supabase.com)
-- ====================================================================

-- --------------------------------------------------------------------
-- 1. PEMBUATAN TABEL DATABASE
-- --------------------------------------------------------------------

-- Tabel Program Kerja (Proker)
CREATE TABLE IF NOT EXISTS public.proker (
  id TEXT PRIMARY KEY,
  title TEXT NOT NULL,
  category TEXT,
  status TEXT,
  date TEXT,
  description TEXT,
  objective TEXT,
  target TEXT,
  impact TEXT,
  image TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Tabel Galeri Foto Kegiatan
CREATE TABLE IF NOT EXISTS public.gallery (
  id TEXT PRIMARY KEY,
  title TEXT NOT NULL,
  prokercategory TEXT,
  caption TEXT,
  image TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Tabel Artikel & Modul Edukasi
CREATE TABLE IF NOT EXISTS public.articles (
  id TEXT PRIMARY KEY,
  title TEXT NOT NULL,
  category TEXT,
  author TEXT,
  date TEXT,
  summary TEXT,
  coverimage TEXT,
  content TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Tabel Pesan & Masukan Warga (Contacts)
CREATE TABLE IF NOT EXISTS public.contacts (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  email TEXT,
  message TEXT NOT NULL,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Matikan Row Level Security (RLS) pada tabel agar dapat diakses aplikasi web
ALTER TABLE public.proker DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.gallery DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.articles DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.contacts DISABLE ROW LEVEL SECURITY;


-- --------------------------------------------------------------------
-- 2. PENYIAPAN BUCKET STORAGE & ATURAN HAK AKSES FOTO (POLICIES)
-- --------------------------------------------------------------------

-- Buat Bucket Storage 'kkn-media' publik
INSERT INTO storage.buckets (id, name, public) 
VALUES ('kkn-media', 'kkn-media', true)
ON CONFLICT (id) DO NOTHING;

-- Hapus policy lama jika ada untuk mencegah bentrok
DROP POLICY IF EXISTS "Allow Public Read" ON storage.objects;
DROP POLICY IF EXISTS "Allow Public Insert" ON storage.objects;
DROP POLICY IF EXISTS "Allow Public Update" ON storage.objects;
DROP POLICY IF EXISTS "Allow Public Delete" ON storage.objects;

-- Buat Policy Izin Akses Foto
CREATE POLICY "Allow Public Read" ON storage.objects FOR SELECT USING (bucket_id = 'kkn-media');
CREATE POLICY "Allow Public Insert" ON storage.objects FOR INSERT WITH CHECK (bucket_id = 'kkn-media');
CREATE POLICY "Allow Public Update" ON storage.objects FOR UPDATE USING (bucket_id = 'kkn-media');
CREATE POLICY "Allow Public Delete" ON storage.objects FOR DELETE USING (bucket_id = 'kkn-media');


-- --------------------------------------------------------------------
-- 3. MENGISI DATA AWAL (SEED INITIAL DATA)
-- --------------------------------------------------------------------

-- Data Awal Proker
INSERT INTO public.proker (id, title, category, status, date, objective, target, description, image, impact)
VALUES 
('proker-1', 'Digitalisasi & Branding UMKM Olahan Pangan Lokal', 'Ekonomi & UMKM', 'Selesai', '12 Juli 2026', 'Membantu pelaku UMKM Desa Karangrejo memperluas jangkauan pasar melalui pendaftaran Google Maps, pembuatan kemasan kedap udara, dan materi promosi sosial media.', 'Pelaku UMKM Pangan Lokal Desa Karangrejo', 'Program ini mencakup restrukturisasi kemasan produk lokal, desain label nutrisi modern, pendaftaran Google Business Profile agar mudah ditemukan wisatawan, serta pelatihan pemasaran digital via Instagram & TikTok.', 'https://images.unsplash.com/photo-1556740758-90de374c12ad?auto=format&fit=crop&w=800&q=80', 'UMKM lokal berhasil terdaftar di Google Maps dan mengalami kenaikan jangkauan pesanan digital.'),
('proker-2', 'Edukasi Pemilahan Sampah & Pelatihan Kompos Rumah Tangga', 'Lingkungan', 'Selesai', '15 Juli 2026', 'Meningkatkan kesadaran lingkungan warga Desa Karangrejo terhadap pengelolaan sampah organik dan anorganik skala rumah tangga.', 'Ibu-Ibu PKK & Warga Desa Karangrejo', 'Sosialisasi langsung pembuatan komposter sederhana memanfaatkan ember bekas dan bioaktivator EM4 untuk mengubah limbah dapur menjadi pupuk organik cair yang kaya unsur hara.', 'https://images.unsplash.com/photo-1542601906990-b4d3fb778b09?auto=format&fit=crop&w=800&q=80', 'Tersedianya unit komposter rumah tangga dan modul praktis pengolahan sampah.'),
('proker-3', 'Bimbingan Belajar Bahasa Inggris & Pojok Baca Digital', 'Pendidikan', 'Berjalan', '18 Juli 2026', 'Meningkatkan literasi dan keterampilan berbahasa Inggris anak-anak sekolah dasar di Desa Karangrejo melalui metode gamifikasi interaktif.', 'Siswa Sekolah Dasar Desa Karangrejo', 'Pendirian Pojok Baca anak dengan koleksi buku fisik dan e-book interaktif, disertai kelas belajar Bahasa Inggris mingguan bernuansa permainan dan lagu edukatif.', 'https://images.unsplash.com/photo-1509062522246-3755977927d7?auto=format&fit=crop&w=800&q=80', 'Anak-anak SD rutin mengikuti program Bimbel interaktif setiap akhir pekan.'),
('proker-4', 'Pemeriksaan Kesehatan Gratis & Pencegahan Stunting', 'Kesehatan', 'Selesai', '22 Juli 2026', 'Mendukung posyandu balita dan lansia dalam pemantauan gizi anak serta pemeriksaan tekanan darah dan gula darah.', 'Balita, Ibu Hamil, dan Lansia Desa Karangrejo', 'Kolaborasi dengan bidan desa untuk mendistribusikan PMT (Pemberian Makanan Tambahan) gizi seimbang, edukasi isi piringku untuk cegah stunting, dan cek kesehatan lansia.', 'https://images.unsplash.com/photo-1576091160399-112ba8d25d1d?auto=format&fit=crop&w=800&q=80', 'Warga terskrining kesehatan dan mendapat vitamin serta makanan tambahan gizi.'),
('proker-5', 'Pembuatan Website Profil Resmi Desa & Peta Tematik Digital', 'Teknologi', 'Berjalan', '25 Juli 2026', 'Menyediakan etalase digital dokumentasi KKN dan informasi publik desa agar mudah diakses oleh pihak kampus, warga, dan pengunjung.', 'Perangkat Desa & Masyarakat Luas', 'Pengembangan sistem web berdesain modern yang menyajikan dokumentasi kegiatan KKN, direktori proker, galeri foto interaktif, serta repositori artikel modul.', 'https://images.unsplash.com/photo-1460925895917-afdab827c52f?auto=format&fit=crop&w=800&q=80', 'Publikasi terbuka terpusat untuk akreditasi KKN & portofolio desa.')
ON CONFLICT (id) DO NOTHING;

-- Data Awal Galeri Foto
INSERT INTO public.gallery (id, title, prokercategory, image, caption)
VALUES
('gal-1', 'Sosialisasi Pemilahan Sampah bersama Ibu PKK', 'Lingkungan', 'https://images.unsplash.com/photo-1542601906990-b4d3fb778b09?auto=format&fit=crop&w=800&q=80', 'Sesi demonstrasi pembuatan pupuk komposter dari sisa dapur di Balai Desa Karangrejo.'),
('gal-2', 'Pendampingan Labeling Packaging UMKM Lokal', 'Ekonomi & UMKM', 'https://images.unsplash.com/photo-1556740758-90de374c12ad?auto=format&fit=crop&w=800&q=80', 'Perancangan desain kemasan pouch modern tahan lembab untuk produk lokal.'),
('gal-3', 'Pemeriksaan Kesehatan Posyandu Lansia', 'Kesehatan', 'https://images.unsplash.com/photo-1576091160399-112ba8d25d1d?auto=format&fit=crop&w=800&q=80', 'Cek gratis tekanan darah & asam urat lansia Desa Karangrejo.'),
('gal-4', 'Kelas Bahasa Inggris Ceria Anak SD', 'Pendidikan', 'https://images.unsplash.com/photo-1509062522246-3755977927d7?auto=format&fit=crop&w=800&q=80', 'Anak-anak antusias memperagakan kosakata hewan & warna dalam permainan kelompok.'),
('gal-5', 'Diskusi Koordinasi dengan Kepala Desa Karangrejo', 'Teknologi', 'https://images.unsplash.com/photo-1522071820081-009f0129c71c?auto=format&fit=crop&w=800&q=80', 'Penyampaian progres program kerja mingguan kepada pimpinan desa.')
ON CONFLICT (id) DO NOTHING;

-- Data Awal Artikel Modul
INSERT INTO public.articles (id, title, category, author, date, summary, coverimage, content)
VALUES
('art-1', 'Panduan Praktis Pembuatan Kompos Rumah Tangga Tanpa Bau', 'Lingkungan & Edukasi', 'Tim Lingkungan KKN Kelompok 3', '16 Juli 2026', 'Pelajari langkah mudah mengubah sisa sampah dapur menjadi cairan pupuk organik kaya nutrisi menggunakan bahan sederhana di rumah.', 'https://images.unsplash.com/photo-1542601906990-b4d3fb778b09?auto=format&fit=crop&w=800&q=80', 'Sampah organik skala rumah tangga mencakup lebih dari 60% total volume limbah harian di pedesaan. Jika ditumpuk tanpa pengolahan, sampah ini berpotensi menimbulkan bau tak sedap dan mengundang bibit penyakit.'),
('art-2', 'Strategi Mendaftarkan Usaha Lokal di Google Maps & Business Profile', 'Ekonomi & Digital', 'Tim Ekonomi & IT KKN Kelompok 3', '20 Juli 2026', 'Tutorial step-by-step gratis pendaftaran toko / UMKM desa ke peta digital Google agar mudah ditemukan pelanggan luar kota.', 'https://images.unsplash.com/photo-1556740758-90de374c12ad?auto=format&fit=crop&w=800&q=80', 'Di era digital, calon pembeli atau wisatawan mencari rekomendasi oleh-oleh langsung via smartphone. Jika UMKM Anda terdaftar di Google Maps, pembeli dapat menemukan rute, jam buka, nomor WhatsApp, dan foto produk dalam 1 kali klik.')
ON CONFLICT (id) DO NOTHING;
